### ISSUE TITLE
linux版本deepBSA运行时报错:ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7,) + inhomogeneous part.

### ISSUE THREAD

**Issue by hongyi1128** [lizhao007/DeepBSA#14]
hy@hy-virtual-machine:/mnt/hgfs/虚拟机/运行/DeepBSA_linux_v1.4/bin$ python3 main.py --i pool.vcf --m ED4 --p 1 --p1 0 --p2 1 --p3 1 --s LOWESS --w 0 --t 0  
2023-09-18 08:34:26.237935: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-18 08:34:26.337176: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-09-18 08:34:26.337209: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-09-18 08:34:26.358161: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-09-18 08:34:26.706002: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-09-18 08:34:26.706085: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-09-18 08:34:26.706101: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
----------------------------------------------------------------------------------------------------
file path:pool.vcf
method:ED4
is pretreatment:True
read number:0
Chi-square test:True
Continuity test:True
smooth method:LOWESS
smooth window size:0
threshold:0.0
----------------------------------------------------------------------------------------------------
vcf to excel: 18744902it [01:58, 158210.80it/s]
pretreatment: 100%|████████████████████████████| 7/7 [1:09:56<00:00, 599.54s/it]
pretreatment: 7it [00:39,  5.68s/it]
Traceback (most recent call last):
  File "/mnt/hgfs/虚拟机/运行/DeepBSA_linux_v1.4/bin/main.py", line 95, in <module>
    main(args)
  File "/mnt/hgfs/虚拟机/运行/DeepBSA_linux_v1.4/bin/main.py", line 51, in main
    ref_data_path, mut_data_path, freq_data_path, pos_data_path, chrome_set = pretreat.run(return_path)
  File "/mnt/hgfs/虚拟机/运行/DeepBSA_linux_v1.4/bin/functions/pretreatment.py", line 122, in run
    np.save(ref_data_path, A_data)
  File "/home/hy/miniconda3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 545, in save
    arr = np.asanyarray(arr)

**Comment by hongyi1128** [comment]
此外还有一个报错如下：
hy@hy-virtual-machine:/mnt/hgfs/虚拟机/运行/DeepBSA_linux_v1.4/bin$ python3 main.py --i test.csv --m DL --p 0 --s LOWESS --w 0 --t 0
2023-09-18 14:08:08.130039: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:513: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "/mnt/hgfs/虚拟机/运行/DeepBSA_linux_v1.4/bin/main.py", line 8, in <module>
    from functions.Statistic_Methods import Statistic
  File "/mnt/hgfs/虚拟机/运行/DeepBSA_linux_v1.4/bin/functions/Statistic_Methods.py", line 10, in <module>
    from keras.models import load_model
  File "/home/hy/miniconda3/lib/python3.9/site-packages/keras/__init__.py", line 20, in <module>
    from keras import distribute
  File "/home/hy/miniconda3/lib/python3.9/site-packages/keras/distribute/__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "/home/hy/miniconda3/lib/python3.9/site-packages/keras/distribute/sidecar_evaluator.py", line 17, in <module>
    import tensorflow.compat.v2 as tf
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 140, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 41, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/framework/sparse_tensor.py", line 29, in <module>
    from tensorflow.python.framework import constant_op
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/home/hy/miniconda3/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
    np.object,
  File "/home/hy/miniconda3/lib/python3.9/site-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

尝试了更改numpy的版本也没有用，请问有大佬能解决这些问题吗

**Comment by lizhao007** [comment]
请问示例数据能正常运行吗，或者是自己数据中选取一小部分

**Comment by hongyi1128** [comment]
> 请问示例数据能正常运行吗，或者是自己数据中选取一小部分

老师您好，示例数据也出现同样的报错，并且软件重装也无法解决这个问题

**Comment by hongyi1128** [comment]
老师您好，请问我示例数据也出现同样的问题是因为我电脑原因吗，是否有办法解决？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月9日(周一) 晚上9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizhao007/DeepBSA] linux版本deepBSA运行时报错:ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7,) + inhomogeneous part. (Issue #14)




 
请问示例数据能正常运行吗，或者是自己数据中选取一小部分

**Comment by lizhao007** [comment]
应该是软件没装好，跟服务器有关，你可以试试Windows版本，数据较大的话可以在Linux上先设置一个read阈值筛一下vcf，去掉一些低质量的SNP

**Comment by linshengnan09** [comment]
老师您好，Linux版本我也遇到同样的报错解决不了，请问Windows版本处理多大的vcf文件比较合适，我的vcf文件有2.2g左右，用windows版本处理会闪退。

**Comment by lizhao007** [comment]
你好，Windows上2G的VCF我这边也跑过，没什么问题。你可以先跑一条染色体的试试，看看是不是电脑配置问题，如果还是有问题，方便的话可以把vcf发过来，我这跑一下试试。

**Comment by linshengnan09** [comment]
您好，您的邮件我已收到。祝生活愉快，工作顺利！

**Comment by lizhao007** [comment]
闪退的问题可以试试不预处理 #12

**Comment by xinalbert** [comment]
这个问题是numpy版本的问题，numpy = 1.24 就会直接报错，如果安装numpy=1.23就只会有一个警告，但是数据还是会被保存的。
The issue is related to the version of NumPy. If NumPy is set to 1.24, it will trigger an error directly. However, if NumPy version 1.23 is installed, there will be only a warning, but the data will still be saved.

**Comment by linshengnan09** [comment]
您好，您的邮件我已收到。祝生活愉快，工作顺利！

**Comment by Brycealong** [comment]
把pretreatment.py和none_pretreatment.py脚本里的
        np.save(ref_data_path, A_data)
        np.save(mut_data_path, a_data)
        np.save(freq_data_path, freq_data)
        np.save(pos_data_path, position)
改成
        np.save(ref_data_path, np.array(A_data, dtype=object))
        np.save(mut_data_path, np.array(a_data, dtype=object))
        np.save(freq_data_path, np.array(freq_data, dtype=object))
        np.save(pos_data_path, np.array(position, dtype=object))
可以解决这个问题

**Comment by linshengnan09** [comment]
您好，您的邮件我已收到。祝生活愉快，工作顺利！
