### ISSUE TITLE
How can I solve the "Aborted (core dumped)"

### ISSUE THREAD

**Issue by xizhesun** [lizhao007/DeepBSA#4]
Dear developers,

Do you have any suggestions about this?

the command line I  used was as follows:
`python3 ~/tools/DeepBSA_linux_v1.4/bin/main.py -i SR.variants.raw.vcf`

Only the following information is displayed.
> Aborted (core dumped)

I have installed the requirement in "requirment.txt" as follows:

```
conda create -n deepbsa python=3.7

conda activate deepbsa

conda install -c conda-forge pandas=1.1.5
conda install -c conda-forge matplotlib=3.5.3
conda install -c conda-forge statsmodels=0.13.2
conda install -c anaconda tensorflow=2.10.0
conda install -c conda-forge rpy2=3.5.4
conda install -c conda-forge pyinstaller
conda install -c conda-forge tqdm
conda install -c conda-forge keras
```

**Comment by lizhao007** [comment]
Have you tried the test data?

**Comment by xizhesun** [comment]
Hi,

Thank you. I have fixed this issue. And when I tried the demo data, it showed the following message. Could you help me figure out what's the problem?


```
(deepbsa) mals@bioinformatics:~/tools/DeepBSA_linux_v1.4/demo$ python3 ~/tools/DeepBSA_linux_v1.4/bin/main.py --i test.vcf
2023-03-31 13:59:49.952852: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-31 13:59:50.145727: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-31 13:59:50.187424: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
----------------------------------------------------------------------------------------------------
file path:test.vcf
method:DL
is pretreatment:True
read number:0
Chi-square test:True
Continuity test:True
smooth method:LOWESS
smooth window size:0
threshold:0
----------------------------------------------------------------------------------------------------
vcf to excel: 107393it [00:01, 68317.91it/s]
pretreatment & files exist
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
chrome: 1
get data
Traceback (most recent call last):
  File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/main.py", line 95, in <module>
    main(args)
  File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/main.py", line 74, in main
    dl.run()
  File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/functions/Statistic_Methods.py", line 533, in run
    self.mut_data[chrome_index], self.num_pools)
  File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/functions/Statistic_Methods.py", line 429, in get_data
    "row_finetune" + str(num_pools) + "pool.h5"))
  File "/home/data2/mals/anaconda3/envs/deepbsa/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/data2/mals/anaconda3/envs/deepbsa/lib/python3.7/site-packages/keras/saving/save.py", line 227, in load_model
    f"No file or directory found at {filepath_str}"
OSError: No file or directory found at /home/data2/mals/tools/DeepBSA_linux_v1.4/demo/Models/row_finetune2pool.h5
(deepbsa) mals@bioinformatics:~/tools/DeepBSA_linux_v1.4/demo$ 
```

**Comment by xizhesun** [comment]
Oh Sorry, I have found these models under DeepBSA_linux_v1.4/bin/Models. It works now 😊

**Comment by lizhao007** [comment]
Yes, it seems that your running directory is wrong. Just run the script in the bin/ directory.

**Comment by xizhesun** [comment]
After I successfully run the demo data, I received a new error message "pandas.errors.ParserErro" when using my own data.  I use all kinds of variants as the input file. Do I need to extract SNP as the input file?   

I also search this error message on Google and found this  https://stackoverflow.com/questions/18039057/python-pandas-error-tokenizing-data?page=1&tab=scoredesc#tab-top . It seems we have to optimize our code.



```
(deepbsa) mals@bioinformatics:~/CFQ/F2-BSA/DeepBSA$ python3 ~/tools/DeepBSA_linux_v1.4/bin/main.py --i RtoS.variants.raw.vcf                           
2023-04-01 13:36:42.926615: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Li
brary (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA                                 
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                            
2023-04-01 13:36:43.134834: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due t
o floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.         
2023-04-01 13:36:43.174073: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for 
plugin cuBLAS when one has already been registered                                                                                                     
----------------------------------------------------------------------------------------------------                                                   
file path:RtoS.variants.raw.vcf                                                                                                                        
method:DL                                                                                                                                              
is pretreatment:True                                                                                                                                   
read number:0                                                                                                                                          
Chi-square test:True                                                                                                                                   
Continuity test:True                                                                                                                                   
smooth method:LOWESS                                                                                                                                   
smooth window size:0                                                                                                                                   
threshold:0                                                                                                                                            
----------------------------------------------------------------------------------------------------                                                   
Traceback (most recent call last):                                                                                                                     
  File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/main.py", line 95, in <module>                                                                   
    main(args)                                                                                                                                         
  File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/main.py", line 51, in main                                                                       
    ref_data_path, mut_data_path, freq_data_path, pos_data_path, chrome_set = pretreat.run(return_path)                                                
  File "/home/data2/mals/tools/DeepBSA_linux_v1.4/bin/functions/pretreatment.py", line 87, in run                                                      
    data = pd.read_csv(self.file_path, header=None)                                                                                                    
  File "/home/data2/mals/anaconda3/envs/deepbsa/lib/python3.7/site-packages/pandas/io/parsers.py", line 688, in read_csv                               
    return _read(filepath_or_buffer, kwds)                                                                                                             
  File "/home/data2/mals/anaconda3/envs/deepbsa/lib/python3.7/site-packages/pandas/io/parsers.py", line 460, in _read                                  
    data = parser.read(nrows)                                                                                                                          
  File "/home/data2/mals/anaconda3/envs/deepbsa/lib/python3.7/site-packages/pandas/io/parsers.py", line 1198, in read                                  
    ret = self._engine.read(nrows)                                                                                                                     
  File "/home/data2/mals/anaconda3/envs/deepbsa/lib/python3.7/site-packages/pandas/io/parsers.py", line 2157, in read                                  
    data = self._reader.read(nrows)                                                                                                                    
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read                                                                   
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory                                                       
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows                                                             
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows                                                         
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error                                                               
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 2, saw 2                                                          
                                                                                                                                                       
(deepbsa) mals@bioinformatics:~/CFQ/F2-BSA/DeepBSA$                                                                                                    
```

**Comment by xizhesun** [comment]
I changed line 87 of  "pretreatment.py" to `data = pd.read_csv(self.file_path, header=None, error_bad_lines=False)` .  And it's successfully running.  But it will cause the offending lines to be skipped. I am not sure whether it will cause other influences on the final result.

**Comment by xizhesun** [comment]
Hi again,

The size of VCF file is ~ 11 GB. It has been staying in this step for more than 24h without any error message. Is it normal? 

I remember it has a progress bar in the DeepBSA windows version. How about also showing a progress bar in the terminal of the Linux version? 

> (deepbsa) mals@bioinformatics:~/CFQ/F2-BSA/DeepBSA$ python3 ~/tools/DeepBSA_linux_v1.4/bin/main.py --i RtoS.variants.raw.vcf                           
> 2023-04-01 13:49:13.605460: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Li
> brary (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA                                 
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                            
> 2023-04-01 13:49:13.817402: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due t
> o floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.         
> 2023-04-01 13:49:13.858111: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for 
> plugin cuBLAS when one has already been registered                                                                                                     
> ----------------------------------------------------------------------------------------------------                                                   
> file path:RtoS.variants.raw.vcf                                                                                                                        
> method:DL                                                                                                                                              
> is pretreatment:True                                                                                                                                   
> read number:0                                                                                                                                          
> Chi-square test:True                                                                                                                                   
> Continuity test:True                                                                                                                                   
> smooth method:LOWESS                                                                                                                                   
> smooth window size:0                                                                                                                                   
> threshold:0                                                                                                                                            
> ----------------------------------------------------------------------------------------------------

**Comment by lizhao007** [comment]
Thank you for your suggestion. We are considering adding a progress bar to the next version.

**Comment by xizhesun** [comment]
That's good.  👍
